### ISSUE TITLE
希望右键菜单开启时可以临时禁用

### ISSUE THREAD

**Issue by 1208041822** [sxzxs/explore_select_items#2]
希望右键菜单开启时可以临时禁用

**Comment by Faith-Mian** [comment]
是不是没法判断右键菜单当前状态啊？ahk_exe也没变化

**Comment by sxzxs** [comment]
没找到API判断当时右键菜单是否打开
下面方法不知道可不可靠：
只要右键点击，就禁用功能，但是开启得按ESC键

**Comment by sxzxs** [comment]
已修复，by tebayaki

**Comment by Faith-Mian** [comment]
解决的就是这个todo对吗？右键菜单状态屏蔽功能？通过什么办法判断的呢？

**Comment by sxzxs** [comment]
winhook
