### ISSUE TITLE
定位目录非当前目录

### ISSUE THREAD

**Issue by hot36952** [sxzxs/explore_select_items#4]
比如1级目录有a、b、c，2级目录分别有a1-a3、b1-b3、c1-c3的情况
情况1：在1级目录，按b可定位到b，按回车进入2级目录，按1可定位到b1，使用正常
情况2：在2级目录，按回退键进入1级目录，按b却定位到b1，非当前目录，此时空选任何目录或文件，按回车，按b可定位到b
情况3：在1级目录，按b可定位到b，鼠标双击进入2级目录，按1不能定位到b1，按b却定位到b，非当前目录，此时空选任何目录或文件，按回车，按1可定位到b1
不知道是不是bug
如果必须按回车使当前目录生效的话，希望能自定义热键，因为按回车很容易误操作打开目录或文件。

**Comment by sxzxs** [comment]
修改了一个定位的问题

**Comment by hot36952** [comment]
> 修改了一个定位的问题

下载了新版本，定位还是不行，打开某个目录后，要按回车，当前目录才生效，能否自定义改热键？

**Comment by sxzxs** [comment]
没有你这种情况。。。
要不去我的qq软件群：720101589 发个视频

**Comment by sxzxs** [comment]
已增加退格为空 触发路径刷新
